### ISSUE TITLE
Migrations & Seeders

### ISSUE THREAD

**Issue by geeksareforlife** [NottingHack/hms2#14]
The basic database (members and users) needs to be set up

**Comment by cooperaj** [comment]
To get the testing stuff working really nice we'll need to make sure all pertinent data is seeded rather then relying on input. The factory/faker stuff makes this relatively easy but it is something that needs to be kept in mind as functionality/models are added.

**Comment by geeksareforlife** [comment]
@cooperaj we have the roles and permissions being inputted by a migration.  Seeing as this is fixed data, I am assuming that this is ok?

**Comment by cooperaj** [comment]
The roles and permissions are integral to how the HMS will work (i.e. certain features will be hard coded to show, or not show, dependant on those permissions/roles). They should be migrated as invariably you'll be adding new permissions when you add your new feature.

Users however are transient and so would be seeded for test running purposes. 

N.B. We may decided to migrate and admin user for instance so that there is always a way in

**Comment by geeksareforlife** [comment]
fixed in #26
