### ISSUE TITLE
Allow trustees to delete bookable tools

### ISSUE THREAD

**Issue by Samathy** [NottingHack/hms2#455]
While it is possible to allow Trustees to create bookable tools, there is no clear way for Trustees to delete bookable tools.

This is especially apparent right now because a tool can be created, but bugs #452 #453 prevent it from being useful, and the tool still appears to members.

**Comment by dpslwk** [comment]
Only network team should be creating tools (trustees should have never had access to that button)

There is no delete tool button, no matter what level of access you have
like many things in HMS the idea of deleting a tool is impractical since so many other records are tied to it once its been used so we never bother to code it up, and likely won't ever bother
