### ISSUE TITLE
COVID booking system; Booking hours settable per-zone instead of hackspace-wide

### ISSUE THREAD

**Issue by Finaldeath** [NottingHack/hms2#472]
Feature request: currently the COVID booking system allows us to set a maximum duration of all bookings (currently 3 hours) but nothing per-zone.

Hackspace laser usage would be problematic if this was raised - someone might sit there for 6 hours at a time if it was raised to 6 hours for any area. We've disabled the usual laser bookings and tied it to zonal bookings for now.

Requirement is that we can have a booking time limit on these areas (A0/A2 laser) separate from the normal default. The old laser booking duration was 2 hours if it was going to be a quick tickbox ("Laser area") which changes the duration. Otherwise setting it per-zone would be also fine (and indeed more flexible).

**Comment by dpslwk** [comment]
This is just not possible given the way the `Temporary Access Booking` system works

the issue is that the whole system it build around dragging your booking out first then selecting your area
as your drag select your area its checks the global max booking time and limits the drag to this length

**Comment by themrflibble** [comment]
Thanks for the clarification Matt.
It seems if we want to change the maximum hours for a particular zone in
The Space, it affects every zone and cannot be split. So, this is not a
viable solution.

Therefore, on the tool calendar, can a Bootstrap Alert be placed above (and
perhaps below)
'Access to the space must be booked before this tool is booked [button]
This tool must be booked in order to use it, this is in addition to the
Space Access'

At present, both of the lasers have a maximum booking time of 0 minutes.
This stops people only booking the laser, and not the space. We have had
multiple members not be able to gain access because they assumed that
booking the laser is sufficient.
The above alert will reinforce this message, and I can change back to 120
minutes.

>

**Comment by dpslwk** [comment]
the above alert can (if still wanted) now be added using the new editable Content Blocks for 
`tools.booking.index` and `tools.tool.index`
