### ISSUE TITLE
Minimum Membership Payments

### ISSUE THREAD

**Issue by DauntlessAq** [NottingHack/hms2#562]
In accordance with the contents of [Minimum Membership Payments - Nottinghack Wiki](https://wiki.nottinghack.org.uk/wiki/Minimum_Membership_Payments) 

HMS requires changes such that a variable for minimum membership payment is added. The minimum membership payment will be set at a value of £5.

The payments by standing order will be evaluated, and will be separated into two revenue streams:

1. VAT-able revenue - £5 Membership payments

2. VAT-Exempt donations

a. Any standing order payment under the £5 minimum, such that the payee is not considered a current member of Nottingham Hackspace.

b. The amount paid that exceeds the £5 minimum membership payment.

These changes will be compatible with the current provisions for joint accounts (where the amount must be therefore £10 for each member to be covered for £5)

While not strictly necessary in order to implement the above, it is likely that a new class should be added, where non-members are split into ‘Donating Ex-member’ and Non-donating-Ex-Member.

This will allow monitoring of the groups, and will allow the former group to be contacted (likely monthly) thanking them for their donation, and stating that they can increase their donation above the £5 minimum to become a member again.

It is expected that members that reduce their membership payment below the £5 minimum will also be notified that they will be placed into the Donating Ex-Member Class, and their membership will be revoked with notice.

Controls should be added such that the notification period of the groups can be individually altered (especially during the transition period as this change is implemented).

If you are in the Donating Ex-Member Class, you should be able to toggle the email reminders that you are paying under the £5 minimum in HMS, to avoid repeatedly receiving emails.

Having a method for Trustees to override a members status to paying member even if they pay less than £5 per month, and making up the rest from other members donations, would also be a good idea to allow for exceptions (pay it forwards, hardship, etc.).

**Comment by dpslwk** [comment]
#560 is draft PR with this already in progress

separate ex member groups will not be implemented, so most of the above about that is also not going to happen / be irrelevant 

"Trustees to override a members status"  really should not be implemented since the bookkeep and Vat rules don't allow that
London handle this by having a real minimum of £5 (what the software and bookkeeping uses) and a face minimum of £15
and saying anyone wishing to pay less than face minimum needs to contact first

"making up the rest from other members donations" is not something that can be done, the accounting software is completely separate, moving official payments around is not something HMS can touch

**Comment by Finaldeath** [comment]
Thanks for the feedback Matt, we'll use this byline from the Treasurer and HMS developer on the issue. We'll see how it is implemented and see.
